name: Distribution
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install dependencies
        run: npm install
      - name: Build static website
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
      - name: Create archive
        run: tar -cvjSf openstuder-gateway-webui.tar.bz2 build
      - name: Upload web archive
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: openstuder-gateway-webui.tar.bz2