name: Distribution
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install dependencies
        run: npm install
      - name: Build static website
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
      - name: Create archive
        run: tar -C build -cvjSf openstuder-gateway-webui.tar.bz2 .
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: openstuder-gateway-webui.tar.bz2
          asset_name: openstuder-gateway-webui.tar.bz2
          asset_content_type: application/bzip2